### PR TITLE
Fixed #45 added STRCMP operator and tests

### LINKED ISSUE #45: STRCMP operator
[MySQL docs](http://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html#function_strcmp)

### PR DESCRIPTION
**Pull request by SteveFortune**

### CODE REVIEW

**Comment by SteveFortune** [comment]
Oops.. I left `test.only` in. I'll fix this asap.

**Comment by jwhitfieldseed** [comment]
Thanks! Also, Travis is failing with an eslint error - I forgot to warn you about that :smile: 

Can you fix the lint errors, and maybe install your editor's eslint plugin to catch these before commit? I also have a git `pre-commit` hook that runs `npm run lint --quiet`.

**Comment by SteveFortune** [comment]
Sure - shall do

**Comment by jwhitfieldseed** [comment]
Also - could you add an integration test to `query-tests.js` (not `query-auto-tests.js` because sqlite doesn't have `strcmp`. Thanks!

**Pull request merged**
